version: '3.7'

services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: /bin/sh -c "python manage.py initsuperuser && python manage.py migrate && gunicorn news.wsgi:application --bind 0.0.0.0:${PORT}"
    volumes:
      - .:/code
    ports:
      - 1337:8000
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis:6379
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - redis
      - db

  celery:
    build: .
    command: celery -A news worker -B -l INFO
    volumes:
      - .:/code
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis:6379
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - web
      - redis

  redis:
    image: redis:5-alpine

volumes:
  postgres_data:
